public/css/style.css, public/js/loginValidation.js, src/routes.php, templates/index.phtml
Login with JS validation on email password, AJAX post to API and response to routes
=> Task s1 login form

db/academyPortal_2018-11-26.sql
=> updated db with applicants table

src/Classes/Controllers/DisplayApplicantsController.php, src/Classes/Factories/DisplayApplicantsControllerFactory.php, src/dependencies.php, src/routes.php, templates/displayApplicants.phtml
created displayApplicantsController, Factory, added to route and dependencies
=> Phb s3 t1 display applicants controller etc

public/js/registerUser.js, src/Classes/Controllers/LoginController.php, src/Classes/Controllers/RegisterController.php, src/Classes/Controllers/RegisterUserController.php, tests/Controllers/RegisterControllerTest.php, tests/Controllers/RegisterUserControllerTest.php, tests/Factories/RegisterControllerFactoryTest.php
We fixed the login bug. You should now be able to make a new account and use the given password to login. Files to review include:
- src/Classes/Controllers/RegisterUserController.php
- src/Classes/Controllers/RegisterController.php
- tests/Controllers/RegisterControllerTest.php
- tests/Controllers/RegisterUserControllerTest.php
- tests/Factories/RegisterControllerFactoryTest.php
=> S1 find and fix bug

public/css/addHiringPartner.css, public/css/admin.css, public/css/genericStyles.css, src/routes.php, templates/addHiringPartner.phtml, templates/admin.phtml, templates/registerUser.phtml
- **addHiringPartner.phtml** & **addHiringPartner.css** - Created add hiring partner page 
- **routes.php** - Added a new route for page 
- **admin.phtml** & **admin.css** - added nav button to addPartner route and adjusted styling
- **registerUser.phtml** - adjusted indentation from previous cohort because it was rubbish
=> S2 add hiring partner page

src/Classes/Controllers/AddHiringPartnerPageController.php, src/Classes/Factories/AddHiringPartnerPageControllerFactory.php, src/Classes/Factories/HiringPartnerModelFactory.php, src/Classes/Models/HiringPartnerModel.php, src/Classes/ViewHelpers/AddHiringPartnerPageViewHelper.php, src/dependencies.php, src/routes.php, templates/test.phtml, tests/Controllers/AddHiringPartnerPageControllerTest.php, tests/Factories/AddHiringPartnerPageControllerFactoryTest.php, tests/Factories/HiringPartnerModelFactoryTest.php, tests/Models/HiringPartnerModelTest.php, tests/ViewHelpers/AddHiringPartnerPageViewHelperTest.php
Created a dynamic select dropdown of hiring partner size.
Route is /addHiringPartner
Files to be reviewed:
/Controllers/AddHiringPartnerPageController.php
/Models/HiringPartnerModel.php
/ViewHelpers/AddHiringPartnerPageViewHelper.php
/Factories/AddHiringPartnerPageControllerFactory.php
/Factories/HiringPartnerModelFactory.php
tests/Controllers/AddHiringPartnerPageControllerTest.php
tests/Models/HiringPartnerModelTest.php
tests/ViewHelpers/AddHiringPartnerPageViewHelperTest.php
tests/Factories/AddHiringPartnerPageControllerFactoryTest.php
tests/Factories/HiringPartnerModelFactoryTest.php
=> S2 populate dropdown

public/css/addEventPage.css, public/js/addEventValidationAjax.js, public/js/jsonRequest.js, public/js/loginValidation.js, src/routes.php, templates/addEvent.phtml, templates/index.phtml
Added validation functionality to addEvent form, once it's valid makes a fetch post request to backend API
Files need to be reviewed: 
public/css/addEventPage.css (Lines 75-87)
public/js/addEventValidationAjax.js (everything)
src/routes.php (Lines 19 - 22)
=> S3 submit form ajax

public/css/admin.css, src/settings.php, templates/admin.phtml, templates/registerUser.phtml
Changed class name and added button
=> Task1 1add hiring partner button

src/Classes/Models/HiringPartnerModel.php, tests/Models/HiringPartnerModelTest.php
Model that contains the addHiringPartner and getCompanySize
PS - addHiringPartner will call the company entity but company entity isnt made yet so I left a note.
=> Task1 4 hiring partner model

src/dependencies.php
assigned the factory to $container['GetCompanySizeController']
=> added the GetCompanySizeControllerFactory to DIC

src/Classes/Factories/HiringPartnerModelFactory.php, tests/Factories/HiringPartnerModelFactoryTest.php
Factory for the hiring partner model
=> added factory for the hiring partner model

src/dependencies.php
=> added hp model factory to the DIC

src/Classes/Models/HiringPartnerModel.php
removed backticks, added typehint for HiringPartnerEntities, added docblocks
=> added type hinting, removed backticks, added docblocks

src/Classes/Controllers/GetHiringPartnerController.php, src/Classes/Factories/GetHiringPartnerControllerFactory.php, src/Classes/Models/HiringPartnerModel.php, src/dependencies.php, tests/Controllers/GetHiringPartnerControllerTest.php, tests/Factories/GetHiringPartnerControllerFactoryTest.php
=> Task2 2 get hiring partner controller

src/Classes/Models/HiringPartnerModel.php
updated the get hiring partners method to use a left Join
=> Hot fix update get hiring partners method

src/Classes/Controllers/DisplayHiringPartnerContactPageController.php, tests/Controllers/DisplayHiringPartnerContactPageControllerTest.php
I have added the display hiring partner contact page controller and added tests
=> Task3 8 display hiring partner contact page controller

src/Classes/Factories/DisplayHiringPartnerContactPageControllerFactory.php, tests/Factories/DisplayHiringPartnerContactPageControllerFactoryTest.php
I have added the display hiring partners contact page controller factory and tested it
=> Task3 9 display hiring partners contact page controller factory

src/Classes/Factories/CreateHiringPartnerContactControllerFactory.php, src/dependencies.php, src/routes.php, tests/Factories/CreateHiringPartnerContactControllerFactoryTest.php
Also added them to DIC and routes
=> Task3 14 create hiring partner contact controller factory

public/js/applicantModal.js
Change to use relative path in fetch
=> S1T3 - Fix applicant info display

src/Classes/Controllers/DisplayEventsPageController.php, src/Classes/Models/EventModel.php
removed __invoke return typehint
=> changed template ref, get events method call

public/js/getEvents.js, src/Classes/Models/EventModel.php, templates/EventsPage.phtml
Functions for retireving the events information from the database and displaying it on the vents page.
=> S3t8 get+display events

src/Classes/Controllers/DisplayHiringPartnerPageController.php, src/settings.php
added contacts details to DisplayHiringPartnerPageCOntroller array so taht we will be able to acces the info in the view
=> added contacts details to DisplayHiringPartnerPageCOntroller array

src/settings.php, templates/EventsPage.phtml
Added text input and submit button on the events page for users to search the current events
=> C2t1 add search form

db/academyPortal_2019-11-18.sql
=> created new DB link table

public/js/eventsPage.js
Actually made dropdown functionality work in a predictable manner
=> G1T4 - Version 2! Now with less async!!

src/Classes/Controllers/GetEventsController.php, src/Classes/Models/EventModel.php
Added a search event method to the current EventModel class which queries the db with user search term on the db 'events' event name field (supports partial searching) and returns this data as an array.
=> C2t3 add search event method

public/css/genericStyles.css, src/Classes/Controllers/DisplayApplicantsController.php, src/Classes/Models/ApplicantModel.php, src/settings.php, templates/displayApplicants.phtml
Wrapped the table in a form tag. 
Added spaces CSS file.
Created new $params array, used to store the sorting data.
Removed $order from SQL query.
Changed 'host' back to db, ready for master implementation.
=> Updated for master

public/css/genericStyles.css, src/Classes/Controllers/DisplayApplicantsController.php, src/Classes/Models/ApplicantModel.php, src/settings.php, templates/displayApplicants.phtml
Uses arrows to sort the table of registered applicants by modifying the SQL query.
=> Story 3 - Sort Registered applicants.

src/Classes/Entities/HiringPartnerEntity.php
=> conversion to array function complete. Ready for code review

public/js/eventsPage.js, src/Classes/Models/EventModel.php
Wrote a method in the Event Model taking Event Id as a param, pulls out HP ids in the database that match that event id
=> G2t2 Method to get Hp Ids by Event Id

src/Classes/Controllers/AddHiringPartnerToEventController.php, src/Classes/Models/EventModel.php
brief changes after the main branch was merged
=> G2 t2 doc blocks and method renaming

public/js/eventsPage.js, src/Classes/Controllers/GetEventsController.php
Handled all 6 potential outcomes from the events page. Getting events on page load (sucessfully with events, successfully without events, unsuccessful db request for getting all events) and seraching for events (sucessfully with events matching search, successfully without events matching search, unsuccessful db request for getting all events which match search)
=> C2t5 error handling

public/css/genericStyles.css, public/js/eventsPage.js, templates/EventsPage.phtml
Added functionality to clear search results and refresh the page to display all current events in the db.
=> C2t6 clear search

public/js/eventsPage.js, src/Classes/Entities/EventEntity.php, templates/EventsPage.phtml
fixing whitespace and button location on events page
=> C2 story review edits

public/css/genericStyles.css, public/js/eventsPage.js
=> completed delete function and added button. Ready for code review.

src/Classes/Models/ApplicantModel.php
Code review needed for Task 4 - We've added a new deleteApplicant method to the ApplicantModel and updated the SQL statement in Model with a filter to make sure only it's showing not-deleted.
To test, copy the SQL statement from the code and paste into Sequel Pro and set delete status to 1 on random entries and check on the Registered Applicants page to se if they have been deleted from the table
=> Updated model method with new SQL statement and deleteApplicant function

src/Classes/Controllers/DeleteApplicantController.php, tests/Controllers/DeleteApplicantControllerTest.php
Requirements:
- DeleteApplicantController
- unit test
- return http status 200 or 500
To test:
- Run tests in php unit
=> S1t2 delete applicant controller

db/academyPortal_2020-03-31.sql
Requirements:
- create stages table with id, title, order, deleted
- test data in db
To test:
Import new sql file from db/ into SequelPro. Check table for data and structure.
Run the app in your local browser to check all functionality still works.
=> s2t3-tableDB

src/Classes/Factories/StageModelFactory.php, src/Classes/Models/StageModel.php, src/dependencies.php, tests/Factories/StageModelFactoryTest.php
Created an empty StageModel with database connection, a StageModelFactory and tests file.
=> created new StageModel, StageModelFactory and StageModelFactoryTest files

tests/Models/StageModelTest.php
Added a unit test for the StageModel which I'd previously missed.
=> added unit testing to the StageModel

src/Classes/Controllers/DeleteApplicantController.php, tests/Controllers/DeleteApplicantControllerTest.php
Fixes made:
- Added doc blocks to controller and test file
- Added validation to controller for request data
- Added check against the db if a record exists
- Added json package to response with error messages
To test:
- comment out the if statement on line 36 and closing bracket on line 61.
- send test requests to /deleteApplicant via Postman with an id in the body as json data. eg:
`{"id":"4"}`
=> Story1 code review fixes

src/Classes/Entities/StageEntity.php, tests/Entities/StageEntityTest.php
please run php unit test on StagesEntityTest.php
=> S2 t4 a stages entity

README.md, public/css/genericStyles.css, public/js/applicantModal.js, public/js/deleteApplicant.js, src/Classes/Controllers/DeleteApplicantController.php, src/Classes/Factories/DeleteApplicantControllerFactory.php, src/Classes/Models/ApplicantModel.php, src/dependencies.php, src/routes.php, templates/displayApplicants.phtml, templates/partials/applicantInfoModal.phtml, tests/Controllers/DeleteApplicantControllerTest.php, tests/Factories/DeleteApplicantControllerFactoryTest.php
As a: academy admin
I want: to be able to delete applicants
So that: I can remove applicants who are no longer needed
Requirements:
provide delete button on applicant list page
use soft delete
=> Story1 delete applicants

public/js/stagesPage.js, src/Classes/ViewHelpers/StagesPageViewHelper.php, tests/ViewHelpers/StagesPageViewHelperTest.php
Linking up the front end and delete button for the Stages story.
To test - try to delete a stage via the delete button. The flag for deleted in the stages table should be set to 1, and the order should be set to 0.
Please run unit tests as I had to edit as I added a class to the delete buttons.
=> S2 t9 delete button event handling

public/js/stagesPage.js, src/Classes/Controllers/EditStageController.php, src/Classes/Factories/EditStageControllerFactory.php, src/Classes/Models/StageModel.php, src/dependencies.php, src/routes.php, tests/Controllers/EditStageControllerTest.php, tests/Factories/EditStageControllerFactoryTest.php
- Added editStageController
- with unit test
- Added editStageControllerFactory
- with unit test
- Updated DIC
- Added route
- Updated StageModel
=> Pull request S2T7 - editstage

public/css/genericStyles.css, public/js/Sortable.js, public/js/stageReorder.js, public/js/stagesPage.js, src/Classes/Controllers/DeleteStageController.php, src/Classes/Controllers/DisplayStagesController.php, src/Classes/Controllers/EditStageController.php, src/Classes/Models/StageModel.php, src/Classes/ViewHelpers/StagesPageViewHelper.php, templates/stagesPage.phtml, tests/ViewHelpers/StagesPageViewHelperTest.php
Requirements:
- added Sortable.js file
- added stageReorder.js to create a batch edit package when the list is reordered. Calls the sendEditRequest function in stagesPage.js
- added classes to table body and table rows to make Sortable work, and added id to table rows.
To test:
- drag to reorder records in the browser, check the db to see if the order updates correctly
- clear browser cache, and reload page to check the new order persists
=> S2 t8 sortable fe

src/Controllers/DisplayApplicantsController.php, src/Models/ApplicantModel.php
https://trello.com/c/L48gEbIH/227-3a-update-model-to-accommodate-dropdown-with-query-to-select-unique-cohorts
=> aTask3a - Update Model to accommodate dropdown with query to select unique cohorts

app/routes.php, src/ViewHelpers/DisplayApplicantViewHelper.php, tests/ViewHelpers/DisplayApplicantViewHelperTest.php
Added next stage button and pointed it at new route.
=> Mp story1 t1

tests/Entities/EventEntityTest.php
=> Mp story2 t4

db/academyPortal.sql
updated db schema to include new fields for extra student info in table applicants_additional
=> Updated DB Schema

src/Models/ApplicantModel.php, templates/applicantForm.phtml
edited:
Entities/ApplicantEntity.php (lines 199-205, 69, 24) added getGithubUsername(), updated jsonSerial, githubUsername Property
Models/ApplicantModel.php (lines 348, 371)
templates/applicantForm.phtml (lines 106-117) added githubUsername input to new Student Info dropdown Onboarding Section of 'Edit Applicants' page
Also updated typo in DB Query
=> S1 task3 add GitHub username

src/ViewHelpers/DisplayApplicantViewHelper.php, tests/ViewHelpers/DisplayApplicantViewHelperTest.php
Think this is ready for PR, unit tests work and bug is fixed
=> fixed bug and unit test

src/ViewHelpers/ApplicantFormViewHelper.php, templates/applicantForm.phtml, tests/ViewHelpers/ApplicantFormViewHelperTest.php
Damien and I fixed the problem but made an indenting problem, this fixed now too.
OUTSTANDING: some of the entries in the database table for stages or options don't make sense, might need Mike O to clarify what really needs to be there, it shouldn't affect the code.
=> Story2task1 fix dropdown

src/ViewHelpers/ApplicantFormViewHelper.php, templates/applicantForm.phtml, tests/ViewHelpers/ApplicantFormViewHelperTest.php
Fixed non-existant feild in drop down list
=> Story2 sloths

src/Sanitisers/ApplicantSanitiser.php
Changed the column width for the empty applicant fields to span all 6 columns
=> Story3 sloths

templates/partials/applicantInfoModal.phtml
Added p tag to house the URL for the students' profile
=> added a place for the link to sit within the modal

src/Entities/CompleteApplicantEntity.php, src/Models/ApplicantModel.php, src/Sanitisers/ApplicantSanitiser.php, src/Validators/ApplicantValidator.php, templates/applicantForm.phtml
- added new HTML to applicationForm.phtml (14 new fields in total)
- updated ApplicantModel.php SQL to retrieve and send data to the db
- added additional properties BaseApplicant/CompleteBaseApplicant.php
=> Story 1 task 3/task4

templates/applicantForm.phtml
- added some dynamic elements to the applicantForm.phtml template
=> Final PR for story1

README.md
added the login details to the readme file
=> added the login details to the readme file

db/academyPortal_update_2021-07-26.sql, public/css/applicants.css, public/js/applicantForm.js, public/js/populateDropdowns.js, src/Controllers/API/AddApplicantController.php, src/Controllers/FrontEnd/StudentProfilePageController.php, templates/applicantForm.phtml, templates/newApplicantForm.phtml, templates/partials/layout/header.phtml, templates/studentLogin.phtml
-Adding studentLogin.phtml with CSS
- this need the back-end !
=> Koalas_story2_task 4 merge into Loalas_story2

public/js/nextStageModal.js
Added location.reload(); to next stage function. Line 79. Only code that has been changed or added.
=> added reload function to next stage function

src/ViewHelpers/ApplicantFormViewHelper.php, templates/applicantForm.phtml, tests/ViewHelpers/ApplicantFormViewHelperTest.php
Hi Rayna, as you said earlier, we added a fourth parameter to the stagesDropdown method and changed the logic that checked if the option matches with the current option in order to add the selected attribute in one of the `<option>` tags.
=> Story1 fix edit applicant stage dropdown

db/academyPortal.sql, public/js/applicantModal.js, src/Entities/CompleteApplicantEntity.php, src/Models/ApplicantModel.php, src/Sanitisers/ApplicantSanitiser.php, src/ViewHelpers/DisplayStudentProfileViewHelper.php, templates/applicantForm.phtml, templates/partials/applicantInfoModal.phtml, tests/ViewHelpers/DisplayStudentProfileHelperTest.php
Added option for custom assessment day to the applicant form, and added customAssessmentDay field in database. Also made sure the chosen custom assessment day appears in the pop-up of each applicant.
=> S3 t2 show applicant data in pop up

public/js/eventsPage.js, src/Controllers/API/GetEventsController.php, src/Models/EventModel.php
it should display the number of people attending on the events page if the event has the option of setting the number of attendees
=> S4 t1 create html for badges

public/css/applicants.css, public/js/nextStageModal.js, src/Controllers/API/GetNextStageOptionsController.php, src/Controllers/FrontEnd/ApplicantsPageController.php, src/Entities/BaseApplicantEntity.php, src/Entities/StageEntity.php, src/Models/StageModel.php, src/ViewHelpers/DisplayApplicantViewHelper.php, templates/partials/nextStageModal.phtml, tests/ViewHelpers/DisplayApplicantViewHelperTest.php
All data retrieved and displayed in modal with bootstrap & css to match wireframe.
Unit tests run successfully.
=> S8t2 retrieve stage data

public/js/applicantModal.js, public/js/eventsPage.js, public/scss/_genericStyles.scss, templates/applicants.phtml, templates/events.phtml, templates/partials/applicantInfoModal.phtml
contained jQuery for applicant modal in a function called display app…licant modal, updated script tags to support import export, imported applicant modal to eventspage.js
=> Enabled a modul to open on the events page when an applicant's name is clicked

app/dependencies.php, src/Controllers/FrontEnd/TrainersPageController.php, src/Factories/Controllers/FrontEnd/TrainersPageControllerFactory.php
Updated controller functionality and factory to account for trainer model functionality. Added trainer model to DIC
=> s1t4cut-trainers-page-controller-functionality

app/dependencies.php, app/routes.php, public/js/applicantForm.js, public/js/displaytrainers.js, public/js/populateDropdowns.js, public/scss/_trainer.scss, public/scss/styles.scss, src/Controllers/API/DeleteTrainerController.php, src/Controllers/API/GetApplicationFormController.php, src/Factories/Controllers/API/DeleteTrainerControllerFactory.php, src/Models/TrainerModel.php, src/ViewHelpers/DisplayPastAssessmentDayViewHelper.php, src/ViewHelpers/TrainerTableViewHelper.php, templates/applicantForm.phtml, templates/trainers.phtml, tests/ViewHelpers/TrainerTableViewHelperTest.php
Added functionality to copy and trainer buttons. Added strikethroughs to trainer table for deleted trainers. updated unit tests
=> S1t6cut delete trainer copy email

app/dependencies.php, app/routes.php, public/js/addTrainer.js, public/js/validations.js, src/Controllers/API/AddTrainerController.php, src/Factories/Controllers/API/AddTrainerControllerFactory.php, src/Models/TrainerModel.php, src/Sanitisers/TrainerSanitiser.php, src/Validators/TrainerValidator.php, templates/addTrainer.phtml
Validation, Sanitisation and API created for Add trainer form.
=> S1t9cut js validation

public/js/trainernotesmodal.js, src/ViewHelpers/TrainerTableViewHelper.php, templates/partials/trainerNotesModal.phtml, templates/trainers.phtml, tests/ViewHelpers/TrainerTableViewHelperTest.php
created trainer modal and updated tests
=> S1t7cut trainer modal

public/js/addCourse.js, public/scss/_addCourse.scss, public/scss/styles.scss, src/Controllers/API/AddCourseController.php, src/Controllers/FrontEnd/AddCoursePageController.php, src/Factories/Controllers/FrontEnd/AddCoursePageControllerFactory.php, src/Models/CourseModel.php, src/Sanitisers/CourseSanitiser.php, src/ViewHelpers/TrainerCheckboxViewHelper.php, templates/addCourse.phtml, tests/ViewHelpers/TrainerCheckboxViewHelperTest.php
updated addcourse form trainer outputs and added new function to update courses_trainers link table
=> S2t3cut update add course controller

public/scss/_course.scss, public/scss/styles.scss, src/Models/CourseModel.php, src/ViewHelpers/DisplayCoursesViewHelper.php, tests/ViewHelpers/DisplayCoursesViewHelperTest.php
added striketrough to deleted trainers in course page. changed unit tests and added styling
=> added striketrough to deleted trainers in course page.

public/js/saveApplicant.js
=> s3t1-save url bug fixed

app/settings.php, public/js/addCourse.js, templates/addCourse.phtml
addCourse.js file / addCourse.phtml
Add input boxes
=> course inputs added

src/Controllers/API/CsvController.php, src/ViewHelpers/CsvUploadViewHelper.php, templates/admin.phtml, templates/csvUpload.phtml, templates/partials/layout/nav.phtml
CSV Upload form page gives a slim application error.
Please fix the error, and any others relating to this feature. If the feature is completely broken, please advise Mike and consider spiking the problems.
if fixed, remove the link from the home dashboard and add it under the “Applicants” drop down as “Bulk upload” under “New Applicant” in the same section
CSV File for testing: [csv - Sheet1.csv](https://github.com/iO-Academy/AcademyPortal/files/11139679/csv.-.Sheet1.csv)
=> S1t1 csv bug fix

app/settings.php, src/Models/ApplicantModel.php
Back End - Create method that will update the database: Models/ApplicantModel::updateStudentProfileFields()
=> S2t8 editable student profile update db

app/settings.php, public/scss/_studentProfile.scss, public/scss/styles.scss, src/ViewHelpers/DisplayStudentProfileViewHelper.php, tests/ViewHelpers/DisplayStudentProfileHelperTest.php
=> S2 editable student profile s2 t4

app/settings.php, src/Sanitisers/ApplicantSanitiser.php, tests/Sanitisers/ApplicantSanitiserTest.php
started test stuff but ignore that please. Please just review the stuff in sanitiseApplicant
=> S2 editable student profile t7 sanitise student profile fields

db/academyPortal.sql, public/js/addCourse.js, src/Controllers/API/AddCourseController.php, src/Models/CourseModel.php, templates/addCourse.phtml
we've updated db with new field methods to addCourse and bindParams
=> s5t4-addInputToDb 

.gitignore, README.md, app/settings.php, composer.json, public/js/updateStudentProfile.js, src/ViewHelpers/DisplayStudentProfileViewHelper.php, templates/studentProfile.phtml, tests/ViewHelpers/DisplayStudentProfileHelperTest.php
- Created the JS file, made functionality that works for everything, but only applied it to the "edaid" section 
- Modified code in DisplayStudentViewHelper to add demo edit button to check the JS code works (which it does!)
- Need to uncomment the other event listeners in JS file when we have t4 code & replace the demo code in  DisplayStudentViewHelper with t4 code
- For testing also added a script tag in studentProfile.phtml file (but that won't cause any merge conflicts)
=> S2 editable student profile t5 create update student profile js

.circleci/config.yml, composer.json, composer.lock, phpunit.xml
=> php 8 upgrade

.gitignore, composer.json, composer.lock, package-lock.json, package.json, public/js/lockToggle.js, templates/applicantForm.phtml, templates/partials/layout/head.phtml
the lock checkbox changes from locked to unlock and vice versa
doesn’t actually change editability of the fields from the students perspective
=> S3 t1 add lock checkbox applicant edit page caterpillars

.gitignore, public/js/applicantModal.js, src/Controllers/API/GetNextStageOptionsController.php
- Bug was fixed by changing the studentUrl variable in applicantModal.js on line 56 to the profile page link
- Then in order for it to read the student's id for the proper link, had to concatenate data.id on the end of the link (line 69)
- Added an if statement (is not currently necessary) so if there is no link to an applicant's profile it will tell you "No Link Yet"
=> S5t2 fix profile link bug

db/academyPortal.sql, public/js/toggleCompletedCourses.js, src/Models/CourseModel.php, src/ViewHelpers/DisplayCoursesViewHelper.php, templates/courses.phtml
Output for PR:
1. tabs to switch between present&future and past courses
I have instead added a button that toggles whether to show the completed courses or not at the top of the table with a heading of 'Completed Courses'
2. display past courses in reverse chronological order
The past course display in reverse chronological order so that the course with the most recent end date is displayed first.
Cheers
=> S4 t3 display past courses caterpillars

.gitignore, public/js/addCourse.js, public/js/applicantModal.js, public/scss/_applicants.scss, src/Controllers/API/GetApplicantAptitudeController.php, src/Controllers/API/GetNextStageOptionsController.php, src/Models/AptitudeTestModel.php, templates/applicantForm.phtml, templates/partials/applicantInfoModal.phtml
- Buttons styled to fit portal formats. Added button to edit applicant page next to the aptitude score input.
=> S2t4 tidying buttons caterpillars

public/js/applicantModal.js, public/js/editApplicant.js, public/scss/_applicants.scss, templates/applicantForm.phtml, templates/partials/applicantInfoModal.phtml
Use the aptitude test API:
Add a button in the applicant modal and edit page next to the “Aptitude Sccore” field to retrieve the applicants aptitude score
If no score found, tell the user and leave the field set to “Not yet taken”
Still allow manual entry and edit of the score when editing the applicant.
Error handling 
Buttons made pretty
=> S2 t2 automatically update aptitude score when button clicked for modal caterpillars

README.md, app/settings.php, composer.json, public/js/applicantModal.js, public/js/editApplicant.js, src/Controllers/API/GetApplicantAptitudeController.php, src/Models/AptitudeTestModel.php, templates/applicants.phtml
Add a button in the applicant modal and edit page next to the “Aptitude Sccore” field to retrieve the applicants aptitude score.
If no score found, tell the user and leave the field set to “Not yet taken”
Still allow manual entry and edit of the score when editing the applicant.
Extra features added include an alert.
You will need a user with an email to check a score is being retrieved. 
Please find below the email that will work. 
ashit.gajwani@climate-connect.com. 
You will also need to check the opposite. 
here is an email provided. 
hello@mayden.academy
Below is a link to the trello story
https://trello.com/c/uiJgr5bY/1327-story2getaptitudetestresultforastudentcaterpillars
=> Story2 get aptitude test result for a student caterpillars

public/js/editApplicant.js
Story 2
https://trello.com/c/nKLzle84/550-2-incorrect-error-message-shown
When testing system appears that error message is actually showing correctly - tested all possible error message handling and no issues found.
Only change made is rearrange of code in one JS file to make more readable.
=> reformat some js code

src/Controllers/FrontEnd/StudentProfilePageController.php, src/Models/ApplicantModel.php, templates/404.phtml
Task 2 - create 404 page
Task 3 - validation logic when accessing student profile - if applicant id is not valid or applicant is not yet a student will redirect to 404 page
=> Brainworms story4t2 t3

tests/Controllers/FrontEnd/StudentProfilePageControllerTest.php
Unit tests for Student Profile Page Controller
=> Brainworms story4 t4 unit tests

src/Controllers/FrontEnd/AddApplicantPageController.php, src/Controllers/FrontEnd/AddCoursePageController.php, src/Controllers/FrontEnd/AddEventPageController.php, src/Controllers/FrontEnd/AddHiringPartnerContactPageController.php, src/Controllers/FrontEnd/AddHiringPartnerPageController.php, src/Controllers/FrontEnd/AddTrainerPageController.php, src/Controllers/FrontEnd/AdminPageController.php, src/Controllers/FrontEnd/ApplicantsPageController.php, src/Controllers/FrontEnd/CoursesPageController.php, src/Controllers/FrontEnd/EditApplicantPageController.php, src/Controllers/FrontEnd/EventsPageController.php, src/Controllers/FrontEnd/HiringPartnerPageController.php, src/Controllers/FrontEnd/HomePageController.php, src/Controllers/FrontEnd/PastEventsPageController.php, src/Controllers/FrontEnd/RegisterPageController.php, src/Controllers/FrontEnd/StagesPageController.php, src/Controllers/FrontEnd/TeamPickerPageController.php, src/Controllers/FrontEnd/TrainersPageController.php
- added redirection status code where needed
- fixed undefined array key error => added !empty($_SESSION['loggedIn']) to be able to trigger the redirect if the array key doesn't exist
=> add redirection status code + end fix undefined array key error

src/Controllers/FrontEnd/AddApplicantPageController.php, src/Controllers/FrontEnd/AddCoursePageController.php, src/Controllers/FrontEnd/AddEventPageController.php, src/Controllers/FrontEnd/AddHiringPartnerContactPageController.php, src/Controllers/FrontEnd/AddHiringPartnerPageController.php, src/Controllers/FrontEnd/AddTrainerPageController.php, src/Controllers/FrontEnd/AdminPageController.php, src/Controllers/FrontEnd/ApplicantsPageController.php, src/Controllers/FrontEnd/CoursesPageController.php, src/Controllers/FrontEnd/EditApplicantPageController.php, src/Controllers/FrontEnd/EventsPageController.php, src/Controllers/FrontEnd/HiringPartnerPageController.php, src/Controllers/FrontEnd/HomePageController.php, src/Controllers/FrontEnd/PastEventsPageController.php, src/Controllers/FrontEnd/RegisterPageController.php, src/Controllers/FrontEnd/StagesPageController.php, src/Controllers/FrontEnd/TeamPickerPageController.php, src/Controllers/FrontEnd/TrainersPageController.php
- added redirection status code where needed
- fixed undefined array key error => added !empty($_SESSION['loggedIn']) to be able to trigger the redirect if the array key doesn't exist
=> Brainworms s6 fix redirects in firefox

public/js/applicantForm.js, public/js/populateDropdowns.js, src/Models/ApplicationFormModel.php
added future courses to the dropdown list with a default past course if one selected and added the course name to appear with the date
=> Brainworms s5t2 dropdown logic

src/Models/CourseModel.php
added  getCourseById and updateCourse functions to the course model
=> added getCourseById and updateCourse fucntions to the course model

tests/ViewHelpers/DisplayCoursesViewHelperTest.php
=> fix unit tests for display courses view helper

public/js/addCourse.js, public/js/addEvent.js, public/js/addHiringPartner.js, public/js/addHiringPartnerContact.js, public/js/addTrainer.js, public/js/passwordRandom.js, public/js/saveApplicant.js
Reset selectedTrainerId array each time getSelectedTrainers method is called
=> S1t bug fix

public/js/addCourse.js, public/js/addEvent.js, public/js/addHiringPartner.js, public/js/addHiringPartnerContact.js, public/js/addTrainer.js, public/js/passwordRandom.js, public/js/saveApplicant.js
Fixed error message bug being caused by previous declarations of errorMessage variable
=> Renamed error messages to be more semantic

app/routes.php, public/js/calendarPage.js, src/Abstracts/CourseSplitterHelper.php, src/Controllers/API/AddCourseController.php, src/Controllers/API/CalendarCourseController.php, src/Entities/CalendarCourseEntity.php, src/Entities/CalendarEventEntity.php, src/Models/CourseModel.php
added functionality to display the courses alongside the events
=> Added courses to existing calendar

public/scss/_events.scss
=> colors for courses on calendar

src/Controllers/FrontEnd/EditTrainerPageController.php, src/Models/TrainerModel.php, templates/editTrainer.phtml, tests/ViewHelpers/TrainerTableViewHelperTest.php
Shows edit trainer form page, populated with trainer details
=> Edit trainer page t3

public/js/calendarPage.js, templates/calendar.phtml, templates/partials/calendarModal.phtml
Styling complete.  Issue with end time if it is the following day.  End time will not populate.  Spoke to Matt and agreed that is out of scope
=> Hippo story7 task3 styling
